### ISSUE TITLE
Installation and Question

### ISSUE THREAD

**Issue by ghost** [codebytere/codebytere.github.io#10]
@codebytere,
I will not lie this is a really cool project!!! which leads me to my question would it be cool with you applying this project to my portfolio nicotravassos.co.za which is currently a dead link because I cannot come up with something cool like this 😢.

Second could you kindly add to the README how would I go by publishing this as a production version on a naked Ubuntu server? Requirements and commands would be nice 😋 

Thanks again 🤗

**Comment by codebytere** [comment]
Thanks for reaching out! I'm glad you appreciate my project, but it's deployed as a simple static site through GitHub pages, which means that I did not need to configure it for an Ubuntu server at any point. You are more than welcome, however, to fork this project, figure out how to do what you seek, and then PR those discoveries back to this project for other users.
