### ISSUE TITLE
cat does not understand path argument

### ISSUE THREAD

**Issue by wigy-opensource-developer** [codebytere/codebytere.github.io#26]
Observed:

```sh
root $ cat skills/proficient.txt
Error: file not found in current directory
```

Expected:

The file content is displayed from a directory different from `pwd`

**Comment by codebytere** [comment]
Thanks for the report! Would you be interested in sending a PR?

**Comment by wigy-opensource-developer** [comment]
Sorry, but I am full of tasks at both work, home and community service.

**Comment by uneet7** [comment]
I think it works fine

![Screenshot from 2020-05-04 21-01-27](https://user-images.githubusercontent.com/26304848/80983697-7a5f2000-8e4a-11ea-85d7-a18c903ebe9a.png)

**Comment by codebytere** [comment]
yes - that'd be because it was closed in https://github.com/codebytere/codebytere.github.io/pull/28
