### ISSUE TITLE
Mobile terminal too small

### ISSUE THREAD

**Issue by DhruvaSambrani** [codebytere/codebytere.github.io#36]
The terminal is too small on mobile. Make it longer than wide for small screens.

**Comment by RaviMauryaHootowl** [comment]
Hey, can I take to solve this issue?

**Comment by DhruvaSambrani** [comment]
Probably change the css to increase the width of the terminal 100 or 95% if it is a mobile screen.

**Comment by RaviMauryaHootowl** [comment]
Something like this?

![WhatsApp Image 2020-12-22 at 9 15 19 AM](https://user-images.githubusercontent.com/59064326/102846566-4c106e00-4436-11eb-955a-cb41642e6ced.jpeg)

**Comment by DhruvaSambrani** [comment]
I guess?
Can you fill up the terminal to see how it overflows?

**Comment by RaviMauryaHootowl** [comment]
Looks like this when filled up. 

![WhatsApp Image 2020-12-22 at 10 43 04 AM](https://user-images.githubusercontent.com/59064326/102851725-9861ab00-4442-11eb-99b3-0e4cad900bea.jpeg)

**Comment by DhruvaSambrani** [comment]
The I guess you can send in a PR, referencing this issue. @codebytere has the last say though 😀
