### ISSUE TITLE
Enforce HTTPS? 

### ISSUE THREAD

**Issue by marcosnils** [codebytere/codebytere.github.io#44]
The site can currently be browsed using plain `http`.  

Since it's hosted on GH pages, forcing HTTPS should be trivial to enable. 

Cheers!

https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site

**Comment by codebytere** [comment]
Oops i don't think i've updated settings since i made this in ~2017 and this setting didn't exist back then 😆 thanks, i fixed it up!
